Fit-Calendar/FitCalendar

src/main/webapp/index.jsp, target/classes/main/webapp/index.jsp
i'm testing git branch and pull request
=> test branch hojeong

src/main/webapp/index.jsp, target/classes/main/webapp/index.jsp
=> test commit

pom.xml
=> org.slf4j 오류 해결

src/main/webapp/exerciser/registerForm.jsp, src/main/webapp/myPage/updateProfileForm.css, src/main/webapp/myPage/updateProfileForm.jsp
add: /myPage/updateProfileForm.jsp
=> add: /myPage/updateProfileForm.jsp

src/main/webapp/exerciser/frame.css, src/main/webapp/exerciser/frameFooter.jsp, src/main/webapp/exerciser/frameHeader.jsp
=> add: 공통 jsp 파일

src/main/webapp/matching/matchingMenu/wantRecommendForm.css, src/main/webapp/matching/matchingMenu/wantRecommendForm.jsp
=> add; wantRecommendForm.jsp

src/controller/matchingOptionController/MatchingCreateOptionController.java, src/main/model/service/MatchingManager.java
add: MatchingManager&Controller
=> add: MatchingManager&Controller

src/main/java/controller/matching/MatchingGetRecommendListController.java, src/main/java/controller/matching/MatchingNofityController.java, src/main/java/controller/matching/MatchingRecommendAcceptionController.java, src/main/java/controller/matching/MatchingRecommendRefuselController.java, src/main/java/controller/matching/MatchingStartController.java, src/main/java/controller/matching/MatchingWantListController.java, src/main/java/controller/matching/MatchingWantRecommendForm.java, src/main/java/controller/matching/UpdateMatchingOptionController.java, src/main/java/controller/matching/UpdateMaxMateController.java, src/main/java/model/MatchingStatus.java, src/main/java/model/Recommend.java, src/main/java/model/RecommendList.java, src/main/java/model/dao/MatchingDao.java, src/main/java/model/dao/RecommendDao.java, src/main/java/test/MatchingTest.java
=> add: matching's

src/main/java/controller/exerciser/LoginController.java, src/main/java/model/Exerciser.java, src/main/java/model/service/ExerciserManager.java, src/main/java/model/service/PasswordMismatchException.java, src/main/java/model/service/UserNotFoundException.java, src/main/webapp/WEB-INF/exerciser/loginForm.jsp, src/main/webapp/css/loginForm.css, src/main/webapp/css/registerForm.css
=> fix: login

src/main/java/controller/exerciser/RegisterController.java, src/main/java/model/dao/ExerciserDao.java, src/main/java/model/service/ExerciserManager.java, src/main/java/model/service/ExistingUserException.java
=> feat: 로그인 중복처리

src/main/java/controller/myPage/AttendanceController.java, src/main/java/model/dao/ExerciserDao.java, src/main/java/model/service/ExerciserManager.java
=> fix: 중복 출석 체크 제한

src/main/java/controller/RequestMapping.java, src/main/java/controller/myPage/StaticController.java, src/main/webapp/WEB-INF/myPage/myPageMenu.jsp, src/main/webapp/WEB-INF/myPage/static.jsp, src/main/webapp/css/static.css
=> fix: requset mapping

src/main/java/controller/myPage/StaticController.java, src/main/java/model/Static.java, src/main/java/model/dao/StaticDao.java, src/main/webapp/WEB-INF/myPage/static.jsp
fix: static
아직 통계낼 값 없는 거 처리해야함
=> fix: static

src/main/java/controller/RequestMapping.java, src/main/java/controller/record/AllRecordController.java, src/main/java/controller/record/AllRecordDetailController.java, src/main/java/controller/record/DeleteRecordController.java, src/main/java/controller/record/UpdateRecordController.java, src/main/java/model/dao/RecordDao.java, src/main/java/model/service/RecordManager.java, src/main/webapp/WEB-INF/myRecord/recordForm.jsp, src/main/webapp/WEB-INF/myRecord/updateForm.jsp, src/main/webapp/WEB-INF/record/all/detail.jsp, src/main/webapp/WEB-INF/record/all/list.jsp, src/main/webapp/WEB-INF/record/etc/detail.jsp, src/main/webapp/WEB-INF/record/running/detail.jsp, src/main/webapp/WEB-INF/record/yoga/detail.jsp
=> Record 관련 끝~

src/main/webapp/WEB-INF/frameHeader.jsp, src/main/webapp/css/loginForm.css
=> fix: menu href

src/main/java/controller/RequestMapping.java, src/main/java/controller/exerciser/LoginController.java, src/main/java/controller/exerciser/LogoutController.java, src/main/java/controller/exerciser/UserSessionUtils.java, src/main/webapp/WEB-INF/frameHeader.jsp, src/main/webapp/WEB-INF/main.jsp
add: logout
세션 유틸 사용 가능
로그인 로그아웃 상태에 따라 전환
=> add: logout

src/main/java/model/dao/ExerciserDao.java
=> fix: attendance

src/main/java/controller/myPage/ProfileController.java, src/main/java/controller/myPage/StaticController.java, src/main/java/model/dao/InbodyDao.java, src/main/java/model/service/InbodyManager.java, src/main/webapp/WEB-INF/myPage/myPageMenu.jsp, src/main/webapp/WEB-INF/myPage/profile.jsp, src/main/webapp/css/profile.css, src/main/webapp/css/registerForm.css
=> fix: viewProfile

src/main/java/controller/RequestMapping.java, src/main/java/controller/matching/ListMessageController.java, src/main/java/controller/matching/WriteMessageController.java, src/main/java/model/dao/FitmateDao.java, src/main/java/model/service/FitmateManager.java, src/main/webapp/WEB-INF/exerciser/fitmate/messageForm.jsp, src/main/webapp/WEB-INF/exerciser/fitmate/messageList.jsp, src/main/webapp/WEB-INF/myRecord/recordForm.jsp, src/main/webapp/WEB-INF/myRecord/updateForm.jsp, src/main/webapp/css/messageForm.css, src/main/webapp/css/recordForm.css
=> add : Message 전송

src/main/java/controller/myPage/ProfileController.java, src/main/java/controller/myPage/UpdateProfileController.java, src/main/java/model/Exerciser.java, src/main/java/model/dao/ExerciserDao.java, src/main/java/model/dao/InbodyDao.java, src/main/java/model/dao/StaticDao.java, src/main/java/model/service/ExerciserManager.java, src/main/webapp/WEB-INF/myPage/attendance.jsp, src/main/webapp/WEB-INF/myPage/profile.jsp, src/main/webapp/WEB-INF/myPage/updateProfileForm.jsp, src/main/webapp/css/attendance.css, src/main/webapp/css/registerForm.css
=> fix:update

src/main/java/controller/exerciser/DeleteExerciserController.java, src/main/webapp/WEB-INF/myPage/deleteForm.jsp, src/main/webapp/WEB-INF/myPage/myPageMenu.jsp, src/main/webapp/css/deleteForm.css, src/main/webapp/css/myPageMenu.css
=> deleteForm css

src/main/java/controller/myPage/StaticController.java, src/main/webapp/WEB-INF/myPage/static.jsp
=> Static compareInfo null 처리

src/main/webapp/WEB-INF/exerciser/mainInfo.jsp, src/main/webapp/WEB-INF/myRecord/recordForm.jsp, src/main/webapp/WEB-INF/record/all/list.jsp, src/main/webapp/css/recordForm.css, src/main/webapp/css/wantRecommendForm.css
=> record css

src/main/java/controller/record/AllRecordDetailController.java, src/main/java/controller/record/RecordDetailController.java, src/main/webapp/WEB-INF/record/all/detail.jsp
=> Record 오류 수정

src/main/webapp/WEB-INF/record/all/detail.jsp, src/main/webapp/WEB-INF/record/etc/detail.jsp, src/main/webapp/WEB-INF/record/health/detail.jsp, src/main/webapp/WEB-INF/record/running/detail.jsp, src/main/webapp/WEB-INF/record/yoga/detail.jsp
=> fix: record photo box size

src/main/java/controller/record/ListRecordController.java, src/main/java/model/dao/RecordDao.java, src/main/java/model/service/RecordManager.java, src/main/java/test/RecordTest.java, src/main/webapp/WEB-INF/myRecord/list.jsp
=> add : 나의 운동 기록 페이징

src/main/java/controller/matching/UpdateMatchOptionController.java, src/main/webapp/WEB-INF/exerciser/fitmate/messageList.jsp, src/main/webapp/WEB-INF/matching/endMatching.jsp, src/main/webapp/WEB-INF/matching/getRecommendList.jsp, src/main/webapp/WEB-INF/matching/setMate.jsp, src/main/webapp/WEB-INF/matching/situation.jsp
=> fix css, matchingmenu

src/main/webapp/WEB-INF/exerciser/fitmate/messageList.jsp
=> fix message css

src/main/java/controller/RequestMapping.java, src/main/java/controller/matching/MatchingWantRecommendController.java, src/main/webapp/WEB-INF/matching/getRecommendList.jsp
=> rename file, css 수정
